# Generated by Django 5.2.4 on 2025-07-18 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_newslettersubscriber"),
    ]

    operations = [
        migrations.CreateModel(
            name="PortfolioItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("industry", models.CharField(max_length=255)),
                ("logo", models.ImageField(upload_to="portfolio_logos/")),
                ("website", models.URLField(blank=True)),
                ("blurb", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="TeamMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("role", models.CharField(max_length=255)),
                ("image", models.ImageField(upload_to="team_photos/")),
                ("blurb", models.TextField()),
                ("linkedin", models.URLField(blank=True)),
            ],
        ),
    ]
